/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMeetingsIndexRouteImport } from './routes/_app/meetings/index'
import { Route as AppMeetingsMeetingIdIndexRouteImport } from './routes/_app/meetings/$meetingId/index'
import { Route as AppMeetingsMeetingIdSessionsSessionIdRouteImport } from './routes/_app/meetings/$meetingId/sessions/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIndexRoute = AppMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsMeetingIdIndexRoute =
  AppMeetingsMeetingIdIndexRouteImport.update({
    id: '/meetings/$meetingId/',
    path: '/meetings/$meetingId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMeetingsMeetingIdSessionsSessionIdRoute =
  AppMeetingsMeetingIdSessionsSessionIdRouteImport.update({
    id: '/meetings/$meetingId/sessions/$sessionId',
    path: '/meetings/$meetingId/sessions/$sessionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/meetings/': typeof AppMeetingsIndexRoute
  '/meetings/$meetingId/': typeof AppMeetingsMeetingIdIndexRoute
  '/meetings/$meetingId/sessions/$sessionId': typeof AppMeetingsMeetingIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/meetings': typeof AppMeetingsIndexRoute
  '/meetings/$meetingId': typeof AppMeetingsMeetingIdIndexRoute
  '/meetings/$meetingId/sessions/$sessionId': typeof AppMeetingsMeetingIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/meetings/': typeof AppMeetingsIndexRoute
  '/_app/meetings/$meetingId/': typeof AppMeetingsMeetingIdIndexRoute
  '/_app/meetings/$meetingId/sessions/$sessionId': typeof AppMeetingsMeetingIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/meetings/'
    | '/meetings/$meetingId/'
    | '/meetings/$meetingId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/meetings'
    | '/meetings/$meetingId'
    | '/meetings/$meetingId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/calendar'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/meetings/'
    | '/_app/meetings/$meetingId/'
    | '/_app/meetings/$meetingId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings/': {
      id: '/_app/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AppMeetingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings/$meetingId/': {
      id: '/_app/meetings/$meetingId/'
      path: '/meetings/$meetingId'
      fullPath: '/meetings/$meetingId/'
      preLoaderRoute: typeof AppMeetingsMeetingIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings/$meetingId/sessions/$sessionId': {
      id: '/_app/meetings/$meetingId/sessions/$sessionId'
      path: '/meetings/$meetingId/sessions/$sessionId'
      fullPath: '/meetings/$meetingId/sessions/$sessionId'
      preLoaderRoute: typeof AppMeetingsMeetingIdSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppMeetingsIndexRoute: typeof AppMeetingsIndexRoute
  AppMeetingsMeetingIdIndexRoute: typeof AppMeetingsMeetingIdIndexRoute
  AppMeetingsMeetingIdSessionsSessionIdRoute: typeof AppMeetingsMeetingIdSessionsSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppMeetingsIndexRoute: AppMeetingsIndexRoute,
  AppMeetingsMeetingIdIndexRoute: AppMeetingsMeetingIdIndexRoute,
  AppMeetingsMeetingIdSessionsSessionIdRoute:
    AppMeetingsMeetingIdSessionsSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
